from __future__ import annotations

# Shared opening whitelist used across builders.
# Note: we include a few common spelling/diacritics variants so membership checks work.
OPENING_WHITELIST: set[str] = {
    "Sicilian Defense",
    "French Defense",
    "Caro-Kann Defense",
    "Scandinavian Defense",
    "Alekhine Defense",
    "Pirc Defense",
    "Modern Defense",
    "Dutch Defense",
    "Philidor Defense",
    "Petrov's Defense",
    "Italian Game",
    "Ruy Lopez",
    "Scotch Game",
    "Four Knights Game",
    "Vienna Game",
    "King's Gambit",
    "English Opening",
    "Queen's Gambit",
    "Slav Defense",
    "Semi-Slav Defense",
    "Nimzo-Indian Defense",
    "Queen's Indian Defense",
    "Bogo-Indian Defense",
    "King's Indian Defense",
    "Benoni Defense",
    "Benko Gambit",
    "London System",
    "Catalan Opening",
    "Reti Opening",
    "Bird Opening",
    "Polish Opening",
    "Owen Defense",
    "Czech Defense",
    "Trompowsky Attack",
    "Veresov Opening",
    "Jobava London System",
    "Stonewall Attack",
}
